#!/usr/bin/env python3
"""
check_mc_slab_consistency.py

Run the serial `mc_slab` and pthreads `mc_slab_pthreads` executables across a
set of parameters and confirm their (r,b,t) outputs match within an absolute
threshold.

Usage: run from the `mcnt` directory where the executables live.

Optional arguments:
  --C --Cc --H : physical parameters (defaults chosen for quick tests)
  --ns         : comma-separated list of n particle counts to test (default: 1000,5000,10000)
  --threads    : comma-separated list of thread counts to test (default: 1,2,4,8)
  --seed       : base RNG seed (default: 42)
  --tol        : absolute tolerance for matching fractions (default: 0.005)
  --serial     : path to serial executable (default ./mc_slab)
  --pthreads   : path to pthreads executable (default ./mc_slab_pthreads)

Exit code: 0 if all comparisons within tolerance, non-zero otherwise.
"""

import argparse
import subprocess
import sys
from math import fabs
import os


def run_prog(cmd):
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, check=True)
    except subprocess.CalledProcessError as e:
        print(f"ERROR: command failed: {' '.join(cmd)}")
        print("stdout:\n", e.stdout)
        print("stderr:\n", e.stderr)
        raise
    out = p.stdout.strip()
    parts = out.split()
    if len(parts) < 3:
        raise RuntimeError(f"Unexpected output from {' '.join(cmd)}: '{out}'")
    return tuple(float(x) for x in parts[:3])


def parse_list_int(s):
    return [int(x) for x in s.split(',') if x.strip()]


def geom_seq(start, stop):
    vals = []
    v = int(start)
    while v <= stop:
        vals.append(v)
        v = v * 2
    if vals and vals[-1] < stop:
        vals.append(int(stop))
    return vals


def main():
    parser = argparse.ArgumentParser(description='Compare mc_slab and mc_slab_pthreads outputs')
    parser.add_argument('--C', type=float, default=0.5)
    parser.add_argument('--Cc', type=float, default=0.005)
    parser.add_argument('--H', type=float, default=1.0)
    parser.add_argument('--ns', default=None, help='comma list of n values (optional)')
    parser.add_argument('--n_start', type=int, default=None, help='start n (optional)')
    parser.add_argument('--n_max', type=int, default=None, help='max n (optional)')
    parser.add_argument('--threads', default=None, help='comma list of thread counts (deprecated)')
    parser.add_argument('--Ps', default=None, help='comma list of thread counts (preferred)')
    parser.add_argument('--seed', type=int, default=42)
    parser.add_argument('--trials', type=int, default=1, help='number of trials per (n,P)')
    parser.add_argument('--tol', type=float, default=None, help='legacy tolerance name (deprecated)')
    parser.add_argument('--abs_threshold', type=float, default=0.005, help='absolute difference threshold')
    parser.add_argument('--serial', default='./mc_slab')
    parser.add_argument('--pthreads', default='./mc_slab_pthreads', help='path to pthreads executable (alias for --parallel)')
    parser.add_argument('--parallel', default=None, help='alias for --pthreads')
    parser.add_argument('--results_dir', default=None, help='optional output directory')

    args = parser.parse_args()

    # Resolve serial and parallel executable paths
    serial = args.serial
    pthreads = args.parallel if args.parallel else args.pthreads

    # Resolve ns (either explicit list or generated by start/max)
    if args.ns:
        ns = parse_list_int(args.ns)
    elif args.n_start and args.n_max:
        ns = geom_seq(args.n_start, args.n_max)
    else:
        # default list
        ns = [1000, 5000, 10000]

    # Resolve thread list
    thr_arg = args.Ps if args.Ps else args.threads
    if thr_arg:
        threads = parse_list_int(thr_arg)
    else:
        threads = [1, 2, 4]

    # Resolve tolerance
    tol = args.abs_threshold if args.abs_threshold is not None else (args.tol if args.tol is not None else 0.005)

    # Trials
    trials = max(1, int(args.trials))

    # Results dir (optional)
    if args.results_dir:
        try:
            os.makedirs(args.results_dir, exist_ok=True)
        except Exception:
            pass

    print('Consistency check:')
    print(f'  serial: {serial}')
    print(f'  parallel: {pthreads}')
    print(f'  C={args.C}, Cc={args.Cc}, H={args.H}')
    print(f'  ns={ns}, threads={threads}, seed={args.seed}, trials={trials}, abs_threshold={tol}')
    if args.results_dir:
        print(f'  results_dir: {args.results_dir}')

    failures = []
    total = 0

    # Precompute total for progress printing: total combinations * trials
    total = len(ns) * len(threads) * trials
    idx = 0
    for n in ns:
        for T in threads:
            # Run specified number of trials
            for tr in range(trials):
                idx += 1
                seed = args.seed + tr
                print(f"[ {idx:3d}/{total:3d}] n={n:7d} P={T:2d} - trials={trials}")
                ser_cmd = [serial, str(args.C), str(args.Cc), str(args.H), str(n), '--seed', str(seed)]
                pt_cmd = [pthreads, str(args.C), str(args.Cc), str(args.H), str(n), str(T), '--seed', str(seed)]

                try:
                    r_ser, b_ser, t_ser = run_prog(ser_cmd)
                except Exception as e:
                    print('Serial run failed; aborting')
                    return 2

                try:
                    r_pt, b_pt, t_pt = run_prog(pt_cmd)
                except Exception as e:
                    print('Parallel run failed; aborting')
                    return 3

                dr = fabs(r_ser - r_pt)
                db = fabs(b_ser - b_pt)
                dt = fabs(t_ser - t_pt)

                ok = (dr <= tol) and (db <= tol) and (dt <= tol)

                status = 'PASS' if ok else 'FAIL'
                print(f' n={n:7d} T={T:2d}  serial=({r_ser:.6f},{b_ser:.6f},{t_ser:.6f})  parallel=({r_pt:.6f},{b_pt:.6f},{t_pt:.6f})  diffs=({dr:.6f},{db:.6f},{dt:.6f})  {status}')

                if not ok:
                    failures.append({'n': n, 'T': T, 'trial': tr, 'serial': (r_ser, b_ser, t_ser), 'parallel': (r_pt, b_pt, t_pt), 'diffs': (dr, db, dt)})

    print('\nSummary:')
    print(f'  Tests run: {total}')
    print(f'  Failures : {len(failures)}')

    if failures:
        print('\nFailures detail:')
        for f in failures:
            print(f" n={f['n']} T={f['T']} diffs={f['diffs']}")
        return 1

    print('All tests within tolerance')
    return 0


if __name__ == '__main__':
    sys.exit(main())
